### ISSUE TITLE
numpy issue

### ISSUE THREAD

**Issue by overthink** [AndrewTweddle/CodingChallenge#1]
Hi Andrew.

I'm trying to run your solution but am hitting the following:

Traceback (most recent call last):
  File "coding_challenge.py", line 60, in <module>
    lManufsSeries = getUniqueManufacturersFromDataFrame(listings)
  File "coding_challenge.py", line 57, in getUniqueManufacturersFromDataFrame
    df = np.sort(dataFrame['manufacturer']).unique()
AttributeError: 'numpy.ndarray' object has no attribute 'unique'

This is numpy 1.9.2.

Thanks,

Mark (from sortable.com)

**Comment by AndrewTweddle** [comment]
Hi Mark,

I've seen reports online that there were a lot of breaking changes in numpy 1.9. So that's the most likely cause.

What OS are you using? I've tested on Ubuntu 14.04 with my original configuration of 3rd party libraries (as per the readme.md, except for 1 very minor difference due to an nltk issue). So I've tried on a different OS and I got past the point where you are getting the error.

I tried setting up virtualenv on Windows to test with numpy 1.9.2, but it has a dependency on Visual Studio 2008. And I am staying with friends currently and constrained by an internet cap, so I am having to avoid large downloads.

I will try with numpy 1.9.2 on an Ubuntu VM next. To ensure my configuration is as similar to yours as possible, would you mind running `pip freeze` or `pip list` and posting the list of Python libraries you are using?

Also what Python version are you on (`python --version`)? 
_[32 bit python 2.7.x is preferable due to numpy dependencies on Fortran libraries, but maybe that's only an issue on Windows. I needed to `sudo apt-get gfortran` first before numpy 1.7.1 would install on Ubuntu, but if you have numpy 1.9.2 installed then that was probably not an issue for you.]_

I'd like to eliminate a data-specific bug as the cause. Are you testing with the same data sets that are downloadable from the Sortable site (i.e. the same as in the `data/input` folder) or your own data sets?

Regards,
Andrew

**Comment by overthink** [comment]
Ah, fixed!  User error.

I'm on Ubuntu 12.04, but I was using virtualenv to set this up out of habit.  The short form is I don't know how to use `pip`.  Once I invoked it correctly (to get the right version of deps) all was good.  Thanks for the support anyway.
